# Site Info
title:              "AGDB: Animal Games Database"
description:        "This is a database of video games related to animals in which animals are the focus or you can play as an animal."

# Author Info
author_name:        "Liz Lorena Berberena"
author_email:       lizlberberena@gmail.com
github_username:    byliz
twitter_username:   smugcroc

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
language:           en-US

# Pagination Settings
paginate_path: "/pg-:num/"
paginate: 5

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: animal-games-database

# Site Build
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - tzinfo
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  genre:
    output: true
    permalink: /genre/:path
  platform:
    output: true
    permalink: /platform/:path
  species:
    output: true
    permalink: /species/:path
  type:
    output: true
    permalink: /type/:path

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:          "posts"
    values:
      layout:        "post"